apiVersion: v2
name: meowhq-istio
description: A Helm chart that configures Istio CRD and Istiod
type: application
version: 0.0.0
appVersion: 1.24.3
dependencies:
  - name: base
    version: 1.24.3
    repository: https://istio-release.storage.googleapis.com/charts
    condition: base.enabled
  - name: istiod
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.24.3
    condition: istiod.enabled
