apiVersion: v2
name: meowhq-istio
description: A Helm chart that configures Istio CRD and Istiod
type: application
version: 1.0.1
appVersion: 1.24.3
dependencies:
  - name: base
    version: 1.24.6
    repository: https://istio-release.storage.googleapis.com/charts
    condition: base.enabled
  - name: istiod
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.24.6
    condition: istiod.enabled
