# =============================================================================
# global configuration for all components including istio sub-charts istio base and istiod
# istiod subchart uses this global section as well
# please be careful not to put non istiod related configuration here in the global as much as possible
# as istiod subchart will have all the values in the global to the configmap
# https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
# =============================================================================
global:
  # `global.istioNamespace` is being used by istio base and istiod subcharts
  istioNamespace: istio-system
  # `global.imagePullSecrets` is being used by istio base and istiod subcharts
  # be careful with format of the imagePullSecrets. it doesn't need `name` key
  imagePullSecrets: []

# =============================================================================
# istio base Helm Chart configuration
# =============================================================================
base:
  enabled: true
  defaultRevision: default

# =============================================================================
# istiod Helm Chart configuration
# =============================================================================
istiod:
  enabled: true
  ## --------------------------------------------------------------------------
  # global configuration for istiod
  ## --------------------------------------------------------------------------
  global:
    configValidation: true
    ## ------------------------------------------------------------------------
    ## below for the istio-csr integration for Vault PKI - istio multicluster setup
    ## istiod.global.caAddress: "cert-manager-istio-csr.istio-system.svc:443"
    ## ------------------------------------------------------------------------
    # caAddress: "cert-manager-istio-csr.istio-system.svc:443"
    caAddress: ""

    ## ------------------------------------------------------------------------
    ## below for the istio multicluster setup
    ## common values for both Multi Primary and Primary-Remote multicluster setup
    ## * meshID is not required for Remote cluster in Primary-Remote multicluster setup
    ## ------------------------------------------------------------------------
    # meshID: "change-me-to-the-mesh-name"
    # network: "change-me-to-the-network-name"
    # multiCluster:
    #   enabled: true
    #   clusterName: "change-me-to-the-cluster-name"
    meshID: ""
    network: ""
    multiCluster:
      enabled: false
      clusterName: ""

    ## ------------------------------------------------------------------------
    ## below for the istio Primary-Remote multicluster setup
    ## ------------------------------------------------------------------------
    # Enable control of remote clusters.
    # - true for Primary cluster for Primary-Remote multicluster setup
    externalIstiod: false
    # Configure a remote cluster as the config cluster for an external istiod.
    # - true for Remote cluster for Primary-Remote multicluster setup
    configCluster: false

    ## ------------------------------------------------------------------------
    ## proxy config - sidecar
    ## ------------------------------------------------------------------------
    proxy:
      logLevel: info
      # Resources for the sidecar.
      resources:
        # default values in istiod chart are 100m and 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
        # default values in istiod chart are 2000m and 1024Mi
        limits:
          cpu: 200m
          memory: 128Mi

  ## --------------------------------------------------------------------------
  ## below is for mesh configuration
  ## https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/
  ## --------------------------------------------------------------------------
  meshConfig:
    accessLogFile: /dev/stdout
    ## ------------------------------------------------------------------------
    ## below is to enable tracing with otel-tracing extension
    ## ------------------------------------------------------------------------
    # enableTracing: true
    # extensionProviders:
    # - name: otel-tracing
    #   opentelemetry:
    #     port: 4317
    #     service: otelc-collector.opentelemetry-operator.svc.cluster.local
    # defaultProviders:
    #   tracing:
    #     - otel-tracing
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      ## ----------------------------------------------------------------------
      ## below is for the istio multicluster setup: defaultConfig.proxyMetadata
      ## https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/
      ## ----------------------------------------------------------------------
      # proxyMetadata:
      #   # Enable basic DNS proxying
      #   ISTIO_META_DNS_CAPTURE: "true"
      #   # Enable automatic address allocation, optional
      #   ISTIO_META_DNS_AUTO_ALLOCATE: "true"

    # keeping traffic in-cluster for the following services
    # <https://istio.io/latest/docs/ops/configuration/traffic-management/multicluster/#keeping-traffic-in-cluster>
    serviceSettings:
    - settings:
        clusterLocal: true
      hosts:
      - "*.kube-system.svc.cluster.local"
      - "*.argocd.svc.cluster.local"
      - "*.cert-manager.svc.cluster.local"
      - "*.external-secrets.svc.cluster.local"

  ## --------------------------------------------------------------------------
  ## below is for the pilot config
  ## --------------------------------------------------------------------------
  pilot:
    autoscaleEnabled: true
    autoscaleMin: 2
    cni:
      enabled: false
    podAnnotations:
      # just copying from existing - maybe not needed
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    resources:
      # default values in istiod chart are 500m and 2048Mi
      requests:
        cpu: 10m
        memory: 100Mi
    ## ------------------------------------------------------------------------
    ## below for the istio-csr integration for Vault PKI - istio multicluster setup
    ## ------------------------------------------------------------------------
    # env:
    #   ENABLE_CA_SERVER: false
