{{ if .Values.secretFromExternalSecrets.enabled }}
{{ range $stores := $.Values.secretFromExternalSecrets.secretStores -}}
apiVersion: external-secrets.io/v1beta1
kind: {{ $stores.kind | default "SecretStore" }}
metadata:
  name: {{ required "A name is required" $stores.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  provider:
    {{- toYaml $stores.provider | nindent 4 }}
---
{{ end -}}
{{ end }}
