{{ if .Values.istio.enabled }}
---
metadata:
  name: argocd-server-internal-vs
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '1'
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  gateways:
  {{- range .Values.istio.gateways }}
  - {{.}}
  {{- end }}
  hosts:
  - {{ .Values.istio.virtualService.host }}
  http:
  - route:
    - destination:
        port:
          number: 80
        host: argocd-server
    match:
    - uri:
        prefix: /
{{ end }}
