apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  source:
    repoURL: https://sunggun-yu.github.io/meowhq-helm-charts
    chart: meowhq-nginx
    targetRevision: 1.9.2
    helm:
      valueFiles:
      - values.yaml
      - values-gke.yaml
      values:
        nginx:
          # additional customization
          replicaCount: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
