apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  gateways:
    - istio-system/lab-meowhq-dev-gw
  hosts:
    - {{ .Values.istio.host }}
  http:
    - route:
      - destination:
          host: {{ .Release.Name }}
          port:
            number: {{ .Values.vault.server.service.port }}
