# ------------------------------------------------------------------------------
# values for nginx: GKE, just scenario for testing
# ------------------------------------------------------------------------------

nginx:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
